# fly.toml file generated for todoist-ui-extensions on 2022-11-19T17:25:05Z

app = "todoist-ui-extensions"

[build]
  dockerfile = "server.Dockerfile"

[env]
  PORT = "8080"
  BASE_URL = "https://todoist-ui-extensions.fly.dev"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"
